name: RaidsPerRegion
version: 1.0
api-version: 1.16
author: ShermansWorld
main: me.ShermansWorld.RaidsPerRegion.Main

commands:
  raid:
    aliases: [r]
    description: Used to start raids
    softdepend: [WorldEdit, WorldGuard, MythicMobs]
  raidsperregion:
    aliases: [RaidsPerRegion]
    description: Used to cancel raids or reload plugin