name: RaidsPerRegion
version: 2.1
api-version: 1.18
author: ShermansWorld
main: me.ShermansWorld.RaidsPerRegion.Main
depend: [WorldEdit, WorldGuard, MythicMobs]

commands:
  raid:
    aliases: [Raid]
    description: Used to start raids
    depend: [WorldEdit, WorldGuard, MythicMobs]
  raidsperregion:
    description: Used to cancel raids or reload plugin