# NOTES ON OPEN SOURCE:
# This plugin is an open source project developed by ShermansWorld and KristOJa
# This source code can be found here: https://github.com/ShermansWorld/RaidsPerRegion/
# Feel free to change the code to fit your needs, we just ask that you credit and link the original source code

# NOTES ON PLUGIN/CONFIG:
# Version: 1.0
# RaidsPerRegion is a server event plugin that allows you to conduct a raid on a predefined WorldGuard region
# Players within the region have to kill a set amount of your custom MythicMobs mobs before the timer runs
# A raid is initiated using /raid [region] [tier], it can be cancelled using /raid cancel
# This plugin requires MythicMobs, WorldGuard and WorldEdit as dependencies. Please make sure these pluings are up to date
# Make sure no other plugin is disabling mob spawning in the raid area, like Towny or Factions for example
# This config can be reloaded ingame using /RaidsPerRegion reload

# PERMISSION NODES:
# raidsperregion.raid - Allows access to all /raid commands
# raidsperregion.reload - Allows for /raidsperregion reload

# HELP WITH DEPENDENCIES:
# How to define a WorldGuard Region: https://worldguard.enginehub.org/en/latest/regions/quick-start/

# How to create MythicMobs Mob: https://www.mythicmobs.net/manual/doku.php/start 
# Or look at exampleMobs.yml in your MythicMobs folder


# ------  Title Messages  ---------
# These are the messages to be displayed to all players within the region during a raid
# Use "" for none

# Available Placeholders: @TIER @REGION @SENDER

RaidAnnoucementTitle: "&4&lTier @TIER Raid Inbound"
RaidAnnoucementSubtitle: "&6Prepare to fight!" 

RaidWinTitle: "&2&lRaid Won!"
RaidWinSubtitle: "&6The raiders have fled"

RaidLoseTitle: "&4&lRaid Lost!"
RaidLoseSubtitle: "&6This can't be good..."

RaidCancelledTitle: "&b&LRaid Cancelled"
RaidCancelledSubtitle: "&6Raid Cancelled by @SENDER"




# ------  Mobs that Spawn in Raids  ---------
# These are the mobs (Mythic Mobs) types that spawn in a raid.
# You may edit this section to include as many mobs as you want

# Chance: the chance of spawning in each cycle.
# 0.60 for example would be 60%. The smallest chance can be 0.001 or 0.1%

# Priority: is the priority of the mob spawning. 
# If two mobs spawn per the chance parameter the one with the higher priority is spawned. 
# This means that rare mobs (one with a low chance value) should have a higher priority!

# If no mob is spawned using its chance it defaults to the first mob in the list. 
# This should be your most common one and should not make much of a difference

RaidMobs:
  SkeletalMinion:
    Chance: 0.60
    Priority: 1
  StaticallyChargedSheep:
    Chance: 0.35
    Priority: 2
  SkeletalKnight:
    Chance: 0.20
    Priority: 3
  SkeletalKing:
    Chance: 0.15
    Priority: 4
  AngrySludge:
    Chance: 0.05
    Priority: 5



# ------  Raid Tiers  ---------
# These are the settings for each tier of raid. Right now the plugin supports 3 tiers of raids. They must be named accordingly
# You will probably need to play around with these settings (especially KillsGoal and Time) to see what works best for your mobs

# KillsGoal: The amount of mobs the players need to kill to win the raid
# Time: The time (in seconds) the players have to win the raid
# MaxMobsPerPlayer: The maximum amount of raid mobs that can be alive at any given time
# SpawnRateMultiplier: How fast the mobs spawn. 
# MobLevel: The level of the mobs the spawn (increasing damage and health)

Tier1:
   KillsGoal: 100
   Time: 600
   MaxMobsPerPlayer: 10
   SpawnRateMultiplier: 1.0
   MobLevel: 1.0
Tier2:
   KillsGoal: 300
   Time: 900
   MaxMobsPerPlayer: 15
   SpawnRateMultiplier: 1.5
   MobLevel: 5.0
Tier3:
   KillsGoal: 500
   Time: 1200
   MaxMobsPerPlayer: 20
   SpawnRateMultiplier: 2.0
   MobLevel: 10.0